- name: Add Phusion Passenger repo key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7 state=present
  sudo: yes

- name: Install packages to enable apt over HTTPS
  action: apt pkg={{item}} state=installed update_cache=true
  sudo: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Phusion Passenger repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main'
  sudo: yes

- name: Install nginx-extras and passenger
  action: apt pkg={{item}} state=installed update_cache=true
  sudo: yes
  with_items:
    # note: Passenger repo has it's own nginx-extras package.
    - nginx-extras
    - passenger

- name: copy nginx config file default
  sudo: yes
  template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf 

- name: copy nginx config file  config
  sudo: yes
  template: src=templates/default dest=/etc/nginx/sites-enabled/default
#- name: copy index.html
 # template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
- name: restart nginx
  sudo: yes
  service: name=nginx state=restarted


- name: Start nginx
  service: name=nginx state=started
  sudo: yes