- name: Add locale en
  sudo: yes
  lineinfile: dest=/etc/environment line='LC_ALL=en_US.UTF-8'


- name: Add locale
  sudo: yes
  lineinfile: dest=/etc/environment line='LANG=en_US.UTF-8'

- name: 'run local'
  sudo: yes
  shell: 'locale-gen en_US.UTF-8'

- name: Install PostgreSQL dependencies
  sudo: yes
  action: apt pkg={{item}} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
    #- postgresql-contrib
    - postgresql
  tags: 
  - postgresql.pkgs

- name: install setfacl support
  become: yes
  apt: pkg=acl

- name: ensure database is created
  sudo: yes
  sudo_user: postgres
  become_method: sudo
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  become: yes
  become_user: postgres
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  become: yes
  become_user: postgres
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: ensure no other user can access the database
  become: yes
  become_user: postgres
  postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
#- name: Copy valid pg_hba.conf
  #template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.3/main/pg_hba.conf


- name: create apps directory config owned by {{ deploy }}
  sudo: yes
  file: name=~{{ deploy }}/{{ app_name }}/shared/config state=directory owner={{ deploy }} group=www-data mode=2755
  tags:
    p
- name: Copy valid database
  #template: src=default.conf dest=~/shop/shared/config/database.yml
  sudo: yes
  template: src=templates/database.yml dest=~{{ deploy }}/shop/shared/config/database.yml
  tags:
  - copy.database

- name: Copy valid secret
  sudo: yes
  template: src=templates/secrets.yml dest=~{{ deploy }}/shop/shared/config/secrets.yml
